# Generated by Django 4.0.6 on 2022-07-16 21:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_moment_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='photo',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
