# Generated by Django 4.0.6 on 2022-07-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=350)),
                ('category', models.CharField(choices=[('gra', 'Graduação'), ('pos', 'Pós-graduação'), ('vol', 'Trabalhos voluntários'), ('cer', 'Certificações'), ('cur', 'Cursos')], max_length=3)),
            ],
        ),
    ]
