# Generated by Django 4.0.6 on 2022-07-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='link',
            field=models.CharField(max_length=1500),
        ),
    ]
